src/api/index.md
src/guide/comparison.md
src/guide/components.md

2.0 - 8-15 更新

---

src/guide/comparison.md

2.0 - 8-16 更新

---

src/guide/comparison.md

update react comparison after discussion with dan

update react comparison after discussion with dan

---

src/api/index.md

* vm.$slots documentation improvement
* vm.$slots doc fix: 'Render Function' instead of 'Render Functions'
* $vm.slots - improved initial sentence
* additional tweaks to vm. api entry

vm.$slots documentation improvement (#419)

---

src/guide/class-and-style.md

2016.10.6 翻译Class 与 Style 绑定

---

src/guide/state-management.md

state-management.md

---

src/guide/join.md

Updated the link to [http://forum.vuejs.org/c/show-and-tell](http://forum.vuejs.org/c/show-and-tell), original link was a 404.

Update Show and Tell forum link (#469)

---

src/api/index.md

更新 15 16 部分13

---

src/api/index.md

实例方法/事件  实例方法/生命周期

---

src/guide/instance.md

Fix translation error.

---

src/plugins.md

vue2.0插件翻译提交

---

src/guide/installation.md

fix line 76

---

README.md
src/about/index.md

fix link address

---

src/guide/class-and-style.md
src/guide/computed.md
src/guide/syntax.md

完成Guide部分 5 小节 未翻译的部分
完成Guide部分 4 5 6 小节的校验

Update Guide 4 5 6

---

src/guide/index.md

声明式渲染v-指令部分的例子不对，翻译也比较机械。

---

src/guide/render-function.md

Fix code in render-function.md (#486)

---

src/guide/events.md

事件处理器篇校对完成，原译者要不要看看？@dingyiming

proofread events.md

---

src/guide/forms.md

proofread forms.md

---

src/guide/migration.md

单次绑定<sup>弃用

---

src/guide/routing.md
src/guide/unit-testing.md

路由/单元测试  校验

---

src/guide/custom-directive.md

proofread custom-directive.md

---

src/guide/components.md

fix componetns.md

---

src/support-vuejs/index.md

根据官方页面去掉微信打赏和扫一扫

---

src/vuex/api.md

vuex api 部分翻译

---

src/api/index.md

directives, filters, components那里原翻译有误。

修改一些不准确的地方

---

src/guide/migration-vue-router.md

I translated the rest part and made some correction.

translated and revised

---

src/guide/deployment.md
src/guide/single-file-components.md

Deploying For Production

---

src/guide/list.md

wrong word

---

src/api/index.md

v-for when go through Object，first param is val and second param is key

获取官方更新 (#511)

---

src/vuex/testing.md

完成了Vuex testing.md翻译

---

src/guide/index.md

Vue.component('todo' , {   ==>  Vue.component('todo-item', {

correct a mistake

---

src/guide/computed.md

Reverts vuefe/vuefe.github.io#224

Revert "更改鏈接"

---

src/vue-router/essentials/named-routes.md

Params should be the same as the dynamic segment

change userId to id

---

src/vue-router/essentials/named-routes.md

Reverts vuefe/vuefe.github.io#226

Revert "change userId to id"

---

src/vue-router/essentials/named-routes.md

Reverts vuefe/vuefe.github.io#227

Revert "Revert "change userId to id""

---

src/vuex/state.md

具体可参见原英文文档:  http://vuex.vuejs.org/en/state.html

修正注释中说明信息翻译错误的问题

---

src/v2/guide/transitions.md

fix example-4 in transitions.md

fix example-4 in transitions.md

---

src/v2/guide/components.md
src/v2/guide/conditional.md
src/v2/guide/migration.md

1.v-show 不再支持后跟 v-else
2.迁移文档校对 - 已校对至 v-for
/guide/migration.md

1.v-show 不再支持后跟 v-else 2.迁移文档校对-完成至v-for /guide/migration.md

---

src/v2/guide/components.md
src/v2/guide/transitions.md

组件 - 作用域插槽翻译
/guide/components.md

组件 - 作用域插槽翻译 /guide/components.md

---

src/v2/guide/components.md
src/v2/guide/forms.md
src/v2/guide/reactivity.md

1. 【异步组件】翻译校对。
2. 【输入法编辑器】部分翻译
3. 【组件中使用 v-model】内容被回滚。
/guide/components.md
/guide/forms.md

/guide/components.md & /guide/forms.md 校对

---

src/v2/guide/components.md
src/v2/guide/conditional.md

typo and Circular References Between Components

---

src/v2/guide/typescript.md

看到Vue中文站的关于TypeScript Support 的章节还是英文的，便fork下来翻译，望能为Vue尽一点力！
请看下面第三个提交！

翻译 TypeScript.md

---

src/v2/api/index.md
src/v2/guide/conditional.md

keep-alive props and delete comma

keep-alive props and delete comma 

---

src/v2/guide/components.md
src/v2/guide/deployment.md
src/v2/guide/single-file-components.md

Reverts vuefe/vuefe.github.io#317

Revert "Master"

---

src/v2/guide/migration-vue-router.md

update v-link cn

---

src/v2/guide/installation.md

fix CSP environments

---

src/v2/guide/components.md

异步加载，用的应该是Webpack的require.ensure吧

翻译笔误：require -> require.ensure

---

src/v2/guide/installation.md
src/v2/guide/transitioning-state.md

src/v2/guide/transitioning-state.md 校对完成

src/v2/guide/transitioning-state.md 校对完成

---

src/v2/guide/list.md

src/v2/guide/list.md 校对完成

---

src/v2/guide/custom-directive.md
src/v2/guide/list.md

src/v2/guide/custom-directive.md 重新校对
src/v2/guide/list.md 添加译注

src/v2/guide/custom-directive.md 重新校对 & src/v2/guide/list.md 添加译注

---

src/v2/api/index.md

src/v2/api/index.md 合并 cn.vuejs.org 的翻译

src/v2/api/index.md 合并 cn.vuejs.org 的翻译

---

src/v2/api/index.md
src/v2/guide/index.md
src/v2/guide/migration-vue-router.md
src/v2/guide/mixins.md
src/v2/guide/plugins.md
src/v2/guide/reactivity.md
src/v2/guide/syntax.md
src/v2/guide/unit-testing.md

src/v2/guide/syntax.md 重新校对

---

src/v2/guide/computed.md

src/v2/guide/computed.md 重新校对

---

src/v2/guide/events.md
src/v2/guide/team.md

src/v2/guide/events.md 重新校对

---

src/v2/guide/ssr.md

docs: update ssr.md
